language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install gnupg
  - sudo apt-get install openssl
python:
  - "2.7"
  - "3.4"
install:
  - pip install coveralls
  - pip install gnupg
  - pip install psutil
  - pip install subprocess32
  - pip install pytest
  - pip install pytest-pythonpath
  - pip install coverage
  - python setup.py install
script:
  - coverage run --source kryptomime -m py.test
  - coverage report
after_success:
  coveralls
