language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install gnupg
  - sudo apt-get install openssl
python:
  - "2.7"
  - "3.4"
install:
  - pip install gnupg
  - pip install psutil
  - test $TRAVIS_PYTHON_VERSION = 2.7 && pip install subprocess32
  - pip install pytest-pythonpath
  - pip install coverage
  - pip install coveralls
  - python setup.py install
script:
  - coverage run --source kryptomime -m py.test
  - coverage report
after_success:
  coveralls
